import Head from "next/head";
import Homepage from "../components/Homepage";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ethcode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="image">
          <Navbar />
          <Homepage />
        </div>
      </main>
    </>
  );
}
